### ISSUE TITLE
Are elements just hidden or actually not part of the DOM?

### ISSUE THREAD

**Issue by EvanAgee** [apertureless/vue-breakpoints#2]
Hey, great idea and thanks for taking the time to create it!

I'm wondering, are the hidden elements part of the DOM or truly hidden as if a v-if had been used? I'm wanting to avoid loading assets for mobile that are desktop only and vice-versa.

**Comment by apertureless** [comment]
They are not part of the DOM. They only render if the breakpoint or condition is met 
https://github.com/apertureless/vue-breakpoints/blob/master/src/components/showAt.vue#L46-L49

**Comment by suterma** [comment]
I had the same question, wondering if it's more like a v-show or a v-if.

I suggest you document this distinction in the readme. It makes a difference to me. Also, an example of a rendered DOM fragment for each situation would be helpful.

Anyway, thanks for providing this useful tool!
