### ISSUE TITLE
What is a breakpoint?

### ISSUE THREAD

**Issue by martinandersen3d** [apertureless/vue-breakpoints#6]
Hi i dont fully understand the description of a breakpoint? 

Is this related to user scrolling i browser? or is this the order of the elements, before and after current element?

**Comment by edjroot** [comment]
[Google is your friend](https://google.com/search?q=what+is+a+breakpoint).

In short, breakpoints are related to how you adjust your layout depending on screen size. They have nothing to to with Vue necessarily.
